### ISSUE TITLE
aspell missing in .travis.yml.j2

### ISSUE THREAD

**Issue by daniel-wtd** [while-true-do/ansible-galaxy-skeleton#7]
### Type of Report

Bug

### Actual behaviour

Packages are not installed from travis-ci
- aspell
- aspell-en

### Expected behaviour

packages will be installed:

### Implementation

The below part must be adjusted properly:

```
# .travis.yml
# Install python-pip
addons:
  apt:
    packages:
- python-pip
```
